### ISSUE TITLE
How Can I Use Tagging in Mecha CMS?

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha#145]
Hi Taufik,

How can I use tagging in Mecha CMS? Reference from this page https://mecha-cms.com/store/extension/tag

Can you tell me, which code snippet I must add to which page? Thanks.

**Comment by taufik-nurrohman** [comment]
You can use it right away from the Panel. But it requires you to have a child page. Tags field will be disabled in the root page.
