### ISSUE TITLE
Internal server error 500, again when installing

### ISSUE THREAD

**Issue by desbest** [mecha-cms/mecha#289]
### Make sure that your issue is reproducible by doing the following tasks

- [X] I am using application packages whose source code is not optimized for production (source code is not minified).
- [X] I have activated the test mode by changing the `TEST` constant value to `true` in the `.\index.php` file.
- [X] I have made sure that there are files named `error` or `error-x` or `error-y` in the `.\engine\log` folder.

### What installation method did you use?

File

### Describe your issue in the field below

I've tried the steps described in [my previous issue](https://github.com/mecha-cms/mecha/issues/287) and it doesn't work,

As the error is non-descript, showing a video is better.
See this video for details.
https://www.bitchute.com/video/TNdfL4XFoiad/

### Package version

Stable release version (package with semantic version label such as `v1.0.0`)

### Package version number

3,0,0

### What browsers are you seeing the problem on?

Others

### Error logs of the core application if any

```shell
[04-Aug-2024 14:37:53 UTC] PHP Fatal error:  Declaration of Genome::unserialize(string $lot) must be compatible with Serializable::unserialize($serialized) in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/genome.php on line 107
[04-Aug-2024 14:37:53 UTC] PHP Fatal error:  Uncaught Error: Class 'Genome' not found in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php:3
Stack trace:
#0 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require()
#1 [internal function]: {closure}('Hook')
#2 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(164): spl_autoload_call('Hook')
#3 /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/genome.php(3): {closure}()
#4 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require('/home/desbest/p...')
#5 [internal function]: {closure}('Genome')
#6 /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/state.php(3): spl_autoload_call('Genome')
#7 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require('/home/desbest/p...')
#8 [internal function]: {closure}('State')
#9 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(176): spl_autoload_call('State')
#10 /home/desbest/public_html/flatfiletest/mecha3/index.php(25): require('/home/desbest/p...')
#11 { in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php on line 3
[04-Aug-2024 14:37:53 UTC] PHP Fatal error:  Uncaught Error: Class 'Genome' not found in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php:3
Stack trace:
#0 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require()
#1 [internal function]: {closure}('Hook')
#2 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(170): spl_autoload_call('Hook')
#3 [internal function]: {closure}()
#4 {main}
  thrown in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php on line 3
[04-Aug-2024 14:38:43 UTC] PHP Fatal error:  Declaration of Genome::unserialize(string $lot) must be compatible with Serializable::unserialize($serialized) in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/genome.php on line 107
[04-Aug-2024 14:38:43 UTC] PHP Fatal error:  Uncaught Error: Class 'Genome' not found in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php:3
Stack trace:
#0 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require()
#1 [internal function]: {closure}('Hook')
#2 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(164): spl_autoload_call('Hook')
#3 /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/genome.php(3): {closure}()
#4 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require('/home/desbest/p...')
#5 [internal function]: {closure}('Genome')
#6 /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/state.php(3): spl_autoload_call('Genome')
#7 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require('/home/desbest/p...')
#8 [internal function]: {closure}('State')
#9 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(176): spl_autoload_call('State')
#10 /home/desbest/public_html/flatfiletest/mecha3/index.php(25): require('/home/desbest/p...')
#11 { in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php on line 3
[04-Aug-2024 14:38:43 UTC] PHP Fatal error:  Uncaught Error: Class 'Genome' not found in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php:3
Stack trace:
#0 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require()
#1 [internal function]: {closure}('Hook')
#2 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(170): spl_autoload_call('Hook')
#3 [internal function]: {closure}()
#4 {main}
  thrown in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php on line 3
```

### Error log of the extension if any

```
none
```

### Error log of the layout if any

```shell
none
```

### General error logs if any (if the application fails to set a custom error log path, then the error log will usually appear in this location)

```shell
Fatal error: Declaration of Genome::unserialize(string $lot) must be compatible with Serializable::unserialize($serialized) in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/genome.php on line 107

Fatal error: Uncaught Error: Class 'Genome' not found in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php:3 Stack trace: #0 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require() #1 [internal function]: {closure}('Hook') #2 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(164): spl_autoload_call('Hook') #3 /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/genome.php(3): {closure}() #4 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require('/home/desbest/p...') #5 [internal function]: {closure}('Genome') #6 /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/state.php(3): spl_autoload_call('Genome') #7 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require('/home/desbest/p...') #8 [internal function]: {closure}('State') #9 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(176): spl_autoload_call('State') #10 /home/desbest/public_html/flatfiletest/mecha3/index.php(25): require('/home/desbest/p...') #11 { in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php on line 3

Fatal error: Uncaught Error: Class 'Genome' not found in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php:3 Stack trace: #0 /home/desbest/public_html/flatfiletest/mecha3/engine/f.php(1059): require() #1 [internal function]: {closure}('Hook') #2 /home/desbest/public_html/flatfiletest/mecha3/engine/fire.php(170): spl_autoload_call('Hook') #3 [internal function]: {closure}() #4 {main} thrown in /home/desbest/public_html/flatfiletest/mecha3/engine/kernel/hook.php on line 3

```
```

**Comment by taufik-nurrohman** [comment]
You don&rsquo;t have to write PHP error reporting line manually. Mecha already has it set up in conditional statement internally. Simply change the `TEST` constant value to `true` will enable all PHP error reporting. Save changes, delete all log files, then reload the site to see the updated error log messages.

**Comment by taufik-nurrohman** [comment]
I might not yet delete-create the v3.0.0 tag as usual. But since the previous bug has been resolved the `Genome` class should be updated already to fix the last issue.

My suggestion: download the `main` branch then install it then let me know if it gives you the same errors as in version 3.0.0 (dev).

**Comment by desbest** [comment]
I've tried running the branch and I just get **Error 403 Not Authorised,** with no logs, even with `TEST` set to true.

**Comment by taufik-nurrohman** [comment]
403 is not typical error caused by Mecha.

**Comment by desbest** [comment]
The file permissions are normal. 755 for folders and 644 for files.
Deleting all the `.htaccess files doesn't help either.
[See this video for details.](https://old.bitchute.com/video/ss1SDYkRT2Kq/)

**Comment by taufik-nurrohman** [comment]
Downloading the ZIP file from repo will not include the submodules, maybe that&rsquo;s why. After extracting, if you open the `.\lot\x` folder there will contain empty folders. Download it from the site instead, so it will contain all the submodules automatically so it will install.

**Comment by desbest** [comment]
But you told me to download the `main` branch.

> My suggestion: download the `main` branch then install it then let me know if it gives you the same errors as in version 3.0.0 (dev).

I've now downloaded it from both these places and the error still happens.

* github.com
* mecha-cms.com

Minifying the php is set to **off**

**Comment by desbest** [comment]
# Errors shown in web browser
```
[07-Aug-2024 05:37:03 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /home/desbest/public_html/flatfiletest/mecha3-mainbranch-gen/engine/kernel/genome.php on line 1

Fatal error: Exception thrown without a stack frame in Unknown on line 0

Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /home/desbest/public_html/flatfiletest/mecha3-mainbranch-gen/engine/kernel/genome.php on line 1

Fatal error: Exception thrown without a stack frame in Unknown on line 0
```

# Errors from log file

```
[07-Aug-2024 05:42:08 UTC] PHP Parse error:  syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /home/desbest/public_html/flatfiletest/mecha3-mainbranch-gen/engine/kernel/genome.php on line 1
[07-Aug-2024 05:42:08 UTC] PHP Parse error:  syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /home/desbest/public_html/flatfiletest/mecha3-mainbranch-gen/engine/kernel/genome.php on line 1
[07-Aug-2024 05:42:08 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[07-Aug-2024 05:42:08 UTC] PHP Parse error:  syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /home/desbest/public_html/flatfiletest/mecha3-mainbranch-gen/engine/kernel/genome.php on line 1
[07-Aug-2024 05:42:08 UTC] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
```

```

**Comment by taufik-nurrohman** [comment]
> But you told me to download the `main` branch.

Sorry, I mean from the website, there&rsquo;s a dropdown that shows 3.0.0 by default. There&rsquo;s also an option with the label &ldquo;main&rdquo;

**Comment by taufik-nurrohman** [comment]
Any error message that said &ldquo;on line 1&rdquo; is likely come from a PHP file that is minified. Open `.\engine\kernel\genome.php` and see its content. Is it minified?

The token error likely caused by the new PHP attribute that is not supported by your PHP. It should be treated as normal PHP comment in older PHP versions, but since its code is minified and my server does not remove the PHP attribute syntax (because it is not a comment) so that any code that comes after the `#[asdf]` token will be treated as a continuation of a comment on a web server that does not support PHP attributes.

**Comment by desbest** [comment]
I've just tried that now and now although I can see the home page, the about page doesn't work.

![mecha 3 about page doesn't work](https://github.com/user-attachments/assets/71b27dc4-2761-4abc-934f-80e48e011173)

**Comment by taufik-nurrohman** [comment]
That means your web server does not support URL rewrite. You didn&rsquo;t remove the `.htaccess` files, right?

**Comment by desbest** [comment]
All the initial `.htaccess` files still exist

```
/.htaccess
/engine/.htaccess
/lot/.htaccess
/lot/asset/.htaccess
/lot/y/log/.htaccess
```

**Comment by taufik-nurrohman** [comment]
Just one more step, you just need to make sure that URL rewrite feature is available and active.

From the video, I saw some other CMSes are also installed, do they have URL rewrite issue like Mecha?

**Comment by desbest** [comment]
It works now. I just uploaded it somewhere else [like here](https://tynamite.com/mecha3). 
So it was the [CMS I was already using](https://desbest.com/casey) on my website (in the parent directory) causing it.

With that said, how about fixing the v3.0.0 release on github?

**Comment by taufik-nurrohman** [comment]
When I visit the new site, it displays the HTML as plain text for once then it displays as HTML on the second reload.

**Comment by taufik-nurrohman** [comment]
> With that said, how about fixing the v3.0.0 release on github?

Show me the content of the `.htaccess` file in your parent site.

You may truncate/censor certain parts that you think private.

**Comment by desbest** [comment]
[Here it is.](https://gitlab.com/-/snippets/3736591)
I was using the [Stacey CMS v2.3.0](https://github.com/kolber/stacey/tree/v2.3.0)
[It's associated website was archived here.](https://desbest.com/stacey2.3)

**Comment by taufik-nurrohman** [comment]
Not really sure, but the trailing slash enforcing part may cause it to always redirect the URL twice (to add the `/` ending), since Mecha&rsquo;s URL are mostly clean but does not ends with trailing slash by nature.

**Comment by desbest** [comment]
It looks like the v3.0.0 release has been updated. I can now close this issue.
