### ISSUE TITLE
[SECURITY ISSUE] High-Risk Security Vulnerabilities

### ISSUE THREAD

**Issue by Sp1d3rL1** [mecha-cms/mecha#295]
Hello! There are some **security issues** in the latest mechaCMS (3.0.0) and I would like to provide you the details privately via email and get your confirmation.
Is [hi@taufik-nurrohman.com](url) available for this email? I hope to hear from you in time and hopefully we can work together to fix this issue soon!
You can contact me at this email address: [mnss2021@163.com](url), or just reply to this issue.

**Comment by taufik-nurrohman** [comment]
Yes. But if that email does not work, try t[dot]nurrohman77[at]gmail[dot]com, thanks.

**Comment by 751897386** [comment]
I sent an email to [hi@taufik-nurrohman.com](https://github.com/mecha-cms/mecha/issues/url) so you can see if you received it.

**Comment by taufik-nurrohman** [comment]
Okay thanks a lot for the discovery. Please note that the CMS is not yet hit the stable state until a blog post about version 3.0.0 is published. I will push some patch to the files, delete the latest version and re-release using the same version number.

When the blog post is published, I will tell others to replace the existing installation even if they have the same version number.

**Comment by 751897386** [comment]
Well yes, I understand what you mean. 
I would like to apply a CVE for this vulnerability, please don't remove the current version completely, but leave a version number for it. Since no one knows about this issue at the moment, you can fix it by releasing 3.0.1 after the official 3.0.0 release. Anyway, please keep a version number for the current version.😉

**Comment by 751897386** [comment]
Thanks, and please don't be in too much of a hurry, just release it at your normal pace.

**Comment by taufik-nurrohman** [comment]
https://mecha-cms.com/article/version-3-0-1
