### ISSUE TITLE
Email address validation

### ISSUE THREAD

**Issue by breadcat** [mecha-cms/mecha#73]
I've recently tried installing the latest git version of mecha, however I believe I've found a bug with the email [address validation pattern](https://github.com/mecha-cms/mecha/blob/master/knock.php#L216). My email address uses a [.co.uk TLD](https://en.wikipedia.org/wiki/.uk#Active) and therefore isn't accepted.

One [valid regex](http://regexlib.com/REDetails.aspx?regexp_id=174) which appears to work nicely is: `^.+@[^\.].*\.[a-z]{2,}$`
Alternatively you can just delete the whole pattern section and allow `type="email"` to validate it.

**Comment by tovic** [comment]
This repository is going to be the storage of the stable version of Mecha (currently version `1.x.x`). For the development version, you can go to https://github.com/mecha-cms/genome
