### ISSUE TITLE
How can I display Post Thumbnails on Mecha v1

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha#74]
I would like to know if it is possible to display blogpost pictures on the blog homepage in the teaser? With Mecha v2 works so something and with v1?

I would then work with pictures in the blog posts in the editor and the first picture should then be displayed in the Article-Teaser in the Frontend.

How can I achieve this?

Thanks in advance.

**Comment by tovic** [comment]
In Mecha v1, `image` and `images` property already hard-coded so you can just type `$page->image`. You can see the example usage in _portal_ shield.

**Comment by tovic** [comment]
https://github.com/tovic/portal-shield-for-mecha-cms/blob/81756b3f07a804afe97788f75137eb9eec06bc05/portal/index.php

**Comment by AlexL777** [comment]
OK, Thanks. 

The Portal Shield I have now installed with me and I still try the thumbnails today. Probably the first picture in the blog post is taken as a thumbnail.

This will be appropriate for me.
