### ISSUE TITLE
Is it possible to Work with Youtube Videos on Mecha v1.2.8?

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha#76]
Hi @tovic ,

wanted to ask you if you have an extension for Mecha v1.2.8 already, with which you can embed Youtube videos?

Is it somehow possible or have you not thought of it yet?

Thanks in advance.

**Comment by tovic** [comment]
http://mecha-cms.com/2016/article/useful-shortcodes#reference:youtube-video-embed
