### ISSUE TITLE
Tovic, did you get my donation through PayPal yet?

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/mecha#78]
Hello @tovic ,

How are you and your CMS project? I just donated 15 USD to you and hope that it will motivate you again.

I love Mecha CMS and will continue to do so. I was a bit overwhelmed because I had about 100 CMS projects online. Now most deleted and have more time for important projects.

Can I already update my extensions and plugins because I use Mecha 2.0.1? It would be interesting to learn.

So then head up and together we can do it again :-)

**Comment by tovic** [comment]
Yes I have recieved it, thanks a lot. Current development version, documentation and articles are mostly created for the `v2.2.x` so I **wouldn&rsquo;t** recommend you to update the CMS now. There are some specification changes that makes the control panel extension breaks.

For more information please take a look on the [issue page of the development version](https://github.com/mecha-cms/genome/issues).

**Comment by AlexL777** [comment]
OK, Tovic, Thanks for the hints!
