### ISSUE TITLE
Nginx Configuration Example

### ISSUE THREAD

**Issue by petermoo** [mecha-cms/mecha#81]
I could not find an Nginx configuration example so I used the following.

``` nginx
server {
    listen       80;
    server_name  mecha.local;
    access_log  /home/example/web/mecha/access-logs/access.log;
    error_log /home/example/web/mecha/access-logs/error.log;
    root /home/peter/example/mecha/public_html;
    index  index.php;

    location / {
        try_files $uri $uri/ @rewrite;
    }
    
    # Include PHP 7 config.
    include /home/example/web/nginx.php7.conf;
    
    location @rewrite {
        rewrite ^/(.*)$ /index.php?_=$1? last;
    }

}
```

**Comment by taufik-nurrohman** [comment]
You may need to include the query string as well?

~~~ .nginx
/index.php?_=$1?$args
~~~

**Comment by petermoo** [comment]
Adding the two subdirectory excludes. Removed ? from rewrite to automatically append the query.
`server {
    listen       80;
    server_name  mecha.local;
    access_log  /home/example/web/mecha/access-logs/access.log;
    error_log /home/example/web/mecha/access-logs/error.log;
    root /home/peter/example/mecha/public_html;
    index  index.php;
    
    location ^~ /engine {
        deny all;
        return 404;
    }
    location ^~ /lot {
        deny all;
        return 404;
    }
    
    location / {
        try_files $uri $uri/ @rewrite;
    }
    
    # Include PHP 7 config.
    include /home/example/web/nginx.php7.conf;
    
    location @rewrite {
        rewrite ^/(.*)$ /index.php?_=$1 last;
    }

}`

**Comment by taufik-nurrohman** [comment]
What will happen with the `.\lot\asset`, `.\lot\layout\asset` and `.\lot\x\*\lot\asset` folder then? They must be accessible in public.

**Comment by petermoo** [comment]
I found the CSS problem and added two allows for it. The lot/x/*/lot/asset problem is an estimate as I did not find a test for it. 
`server {
    listen      80;
    server_name mecha.local;
    access_log  /home/example/web/mecha/access-logs/access.log;
    error_log   /home/example/web/mecha/access-logs/error.log;
    root        /home/example/web/mecha/public_html;
    index index.php;
    
    location ^~ /engine {
        deny all;
        return 404;
    }
    
    # The following allow has to be before lot deny.
    location ~  /lot/x/.*/lot/asset/ { allow all; }
    location ^~ /lot {
        deny all;
        return 404;
    }
    location ^~ /lot/asset        { allow all; }
    location ^~ /lot/layout/asset { allow all; }
    
    location / { try_files $uri $uri/ @rewrite; }
    
    # Include PHP 7 config.
    include /home/example/web/nginx.php7.conf;
    
    location @rewrite {
        rewrite ^/(.*)$ /index.php?_=$1 last;
    }
}`

**Comment by petermoo** [comment]
I am no longer working on a Mecha test site. The test site had no added extensions to test assets in subfolders of x. Any future requirements will have to be worked out by someone else.

**Comment by taufik-nurrohman** [comment]
``` nginx
server {

    listen 443 ssl;

    root /path/to/www;

    index index.php index.html;

    server_name mecha-cms.com;

    # access_log /path/to/www/access-logs/access.log;
    # error_log /path/to/www/access-logs/error.log;

    # include /etc/letsencrypt/options-ssl-nginx.conf;

    location = /favicon.ico {
        allow all;
    }

    location = /robots.txt {
        allow all;
    }

    # Google’s site verification file must be accessible in public!
    # Replace `XXXXXXXXXXXXXXXXX` with your original file suffix
    location = /googleXXXXXXXXXXXXXXXXX.html {
        allow all;
    }

    location / {
        try_files $uri $uri/ @route;
    }

    location ^~ /engine/ {
        deny all;
        return 403;
    }

    location ^~ /lot/ {
        deny all;
        return 403;
    }

    location ~ /lot/layout/asset/ {
        allow all;
    }

    location ~ /lot/x/[^/]+/lot/asset/ {
        allow all;
    }

    location ~ \.php$ {
        include fastcgi_params;
        include snippets/fastcgi-php.conf;
        fastcgi_intercept_errors on;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location @route {
        rewrite ^/(.*)$ /index.php?_=$1 last;
    }

}
```
